services:
    app:
        build:
            context: .
        env_file:
            - .env
        container_name: yandex-new-year-bot
        image: app/yandex-new-year-bot:latest
        restart: "always"
        stop_signal: SIGINT
        volumes:
            - .env:/app/.env
            - logs:/app/logs

volumes:
    logs: